version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  commands:
    # Install poetry
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install
    # Install theme
    - git clone https://github.com/alexandrevicenzi/Flex.git ./Flex
    - poetry run pelican-themes -i ./Flex
    # Publish site
    - poetry run pelican --settings publishconf.py --extra-settings SITEURL=$(printf \"${READTHEDOCS_CANONICAL_URL}\") --output _readthedocs/html/ content/
