name: test

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install system dependencies
        run: sudo apt-get install language-pack-en

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Install theme
        run: |
          git clone https://github.com/alexandrevicenzi/Flex.git
          poetry run pelican-themes -i ./Flex

      - name: Build HTML
        run: poetry run make html

      - name: Check internal links
        run: poetry run make test-links-internal

      - name: Install Vale styles
        run: make install-vale-styles

      - name: Install Vale
        run: |
          curl --location https://github.com/errata-ai/vale/releases/download/v2.9.1/vale_2.9.1_Linux_64-bit.tar.gz --output vale.tar.gz
          mkdir "${GITHUB_WORKSPACE}/bin"
          tar xvfz vale.tar.gz --directory "${GITHUB_WORKSPACE}/bin" vale
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - name: Lint prose
        run: |
          vale --v
          poetry run make lint-prose

      - name: Lint Python
        run: poetry run make lint-python
