name: test

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install theme
        run: |
          git clone https://github.com/alexandrevicenzi/Flex.git
          pelican-themes -i ./Flex

      - name: Build HTML
        run: make html

      - name: Check internal links
        run: make test-links-internal

      - name: Install Vale styles
        run: make install-vale-styles

      - name: Install Vale
        run: |
          curl --location https://github.com/errata-ai/vale/releases/download/v2.6.3/vale_2.6.3_Linux_64-bit.tar.gz --output vale.tar.gz
          mkdir "${GITHUB_WORKSPACE}/bin"
          tar xvfz vale.tar.gz --directory "${GITHUB_WORKSPACE}/bin" vale
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - name: Lint prose
        run: |
          vale --version
          make lint-prose

      - name: Lint Python
        run: make lint-python
