name: test

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install theme
        run: |
          git clone https://github.com/alexandrevicenzi/Flex.git
          pelican-themes -i ./Flex

      - name: Build HTML
        run: make html

      - name: Check internal links
        run: make test-links-internal
